#!/bin/bash
if [[ $# -eq 0 ]]
then
	(cd ../../ && . venv/bin/activate && ./waf --run "my_environment2")
	exit 0
fi
if [[ $1 = gdb ]]
then
	(cd ../../ && . venv/bin/activate && ./waf --run "my_environment2" --command-template="gdb --args %s")
else 
	echo "Unrecognized first argument"
	exit 1
fi

