#!/bin/bash
. ../../venv/bin/activate
if ../../waf build; then
	python test.py
fi
deactivate
exit 0

if [[ $# -eq 0 ]]
then
        (. ../../venv/bin/activate && ../../waf build)
        exit 0
fi

if [[ $1 = gdb ]]
then
        (. ../../venv/bin/activate && ../../waf --run "my_environment" --command-template="gdb --args %s")
else
        echo "Unrecognized first argument"
	echo "Currently only 'gdb' is supported - to enable debugging using gdb"
        exit 1
fi

#!/bin/bash
(. ../../venv/bin/activate && python test.py)
