#!../../venv/bin/python

import sys
import os

for arg in sys.argv:
	if arg == 'build':
		os.system("cd ../.. && ./waf build")
	elif arg == 'configbuild':
		os.system("cd ../.. && ./waf configure && ./waf build")
	elif arg == 'config':
		os.system("cd ../.. && ./waf configure")

for arg in sys.argv:
	if arg == 'test':
		os.system(". ../../venv/bin/activate && python test.py")
	elif arg == 'simple_test':
		os.system(". ../../venv/bin/activate && python simple_test.py")
