#!/bin/bash
if [[ $# -eq 0 ]]
then
  (. ../../venv/bin/activate && ../../waf --run "my_environment")
  exit 0
fi

if [[ $1 = gdb ]]
then
  (. ../../venv/bin/activate && ../../waf --run "my_environment" --command-template="gdb --args %s")
else
  echo "Unrecognized first argument"
  exit 1
fi

