#!/bin/bash
if [[ $# -eq 0 ]]
then
	(cd ../../ && . venv/bin/activate && ./waf --run "wifi_env_flags_environment")
	exit 0
fi
if [[ $1 = gdb ]]
then
	(cd ../../ && . venv/bin/activate && ./waf --run "wifi_env_flags_environment" --command-template="gdb --args %s")
else 
	echo "Unrecognized first argument"
	exit 1
fi

